{{- include "common.deployment" (list . "nodered.deployment") -}}
{{- define "nodered.deployment" -}}
spec:
  template:
    spec:
      containers:
        - name: node-red
          image: "nodered/node-red:1.3.5"
          imagePullPolicy: IfNotPresent
          env:
            - name: "FLOWS"
              value: "flows.json"
            - name: "NODE_OPTIONS"
              value: 
            - name: "NODE_RED_ENABLE_PROJECTS"
              value: 
            - name: "NODE_RED_ENABLE_SAFE_MODE"
              value: 
            - name: "TZ"
              value: "UTC"
          ports:
            - name: http
              containerPort: 1880
              protocol: TCP
{{- end -}}
       