{{- include "common.deployment" (list . "nodered.deployment") -}}
{{- define "nodered.deployment" -}}
spec:
  template:
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: data
        env:
        - name: "FLOWS"
          value: "flows.json"
        - name: "NODE_OPTIONS"
          value: 
        - name: "NODE_RED_ENABLE_PROJECTS"
          value: 
        - name: "NODE_RED_ENABLE_SAFE_MODE"
          value: 
        - name: "TZ"
          value: "UTC"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "common.fullname" . }}
{{- end -}}
       